---
kind: pipeline
name: default
steps:
- name: docker
  image: docker.io/plugins/docker
  settings:
    registry: reg.fredhs.net
    username:
       from_secret: harbor_user
    password:
       from_secret: harbor_password
    repo: reg.fredhs.net/r/unrar
    dockerfile: Dockerfile
    purge: true
    auto_tag: false
    tags:
    - latest